# Generated by Django 3.0.7 on 2020-11-02 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201102_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(default=uuid.UUID('9f6adf72-1d3a-11eb-8666-d80f997aad5f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
