# Generated by Django 3.0.7 on 2020-11-03 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201103_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.Answer'),
        ),
    ]
